version: '3.2'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
     - ./postgres/data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "5000:5000"
    restart: on-failure
    depends_on:
      - db
    env_file: 
      - ./.env
    volumes:
      - ./:/app
    command: python index.py
